Repository mattermost/mattermost-app-zendesk, pull requests merged in 2021-05, with the labels that each got.

#44 Fix multiple ticket issues in Zendesk
  Makefile
  package-lock.json
  package.json
  src/app/app.ts
  src/bindings/post_menu.ts
  src/bindings/slash_commands.ts
  src/clients/zendesk.ts
  src/manifest.json
  src/restapi/fConfig.ts
  src/restapi/fConnect.ts
  src/restapi/fDisconnect.ts
  src/restapi/fIncomingWebhooks.ts
  src/store/config.ts
  src/types/apps.ts
  src/utils/utils.ts
Labels: 4: Reviews Complete

#48 Update README.md
  README.md
Labels: 2: Dev Review

#50 Update README.md
  README.md
Labels: 2: Dev Review

#49 Remove channel picker
  src/forms/subscriptions.ts
  src/utils/constants.ts
  src/utils/helper_classes/fields/fields_builder.ts
Labels: QA Review Done

#52 Allow updating shared access_token via slash command and not through config modal
  README.md
  src/bindings/channel_header.ts
  src/bindings/index.ts
  src/bindings/post_menu.ts
  src/bindings/slash_commands.ts
  src/forms/zendesk_config.ts
  src/restapi/fConfig.ts
  src/restapi/fConnect.ts
  src/restapi/fDisconnect.ts
  src/restapi/fHelp.ts
  src/restapi/fTarget.ts
  src/types/apps.ts
  src/utils/ZDTypes.ts
  src/utils/constants.ts
  src/utils/utils.ts
Labels: 2: Dev Review, 3: QA Review

#53 Add lint rule for avoiding floating promises
  .eslintrc.json
  src/forms/subscriptions.ts
  src/restapi/fConfig.ts
  src/restapi/fTarget.ts
Labels: 2: Dev Review

#51 Store is_agent in the oauth2user store
  .eslintrc.json
  README.md
  src/app/app.ts
  src/bindings/channel_header.ts
  src/bindings/index.ts
  src/bindings/post_menu.ts
  src/bindings/slash_commands.ts
  src/clients/mattermost_proxy_plugin.ts
  src/clients/zendesk.ts
  src/forms/create_ticket.ts
  src/forms/subscriptions.ts
  src/forms/zendesk_config.ts
  src/restapi/fConfig.ts
  src/restapi/fConnect.ts
  src/restapi/fDisconnect.ts
  src/restapi/fHelp.ts
  src/restapi/fMe.ts
  src/restapi/fTarget.ts
  src/types/apps.ts
  src/utils/ZDTypes.ts
  src/utils/constants.ts
  src/utils/utils.ts
Labels: 4: Reviews Complete, QA Review Done

#46 bump version to v0.2.1
  src/manifest.json
Labels: 4: Reviews Complete

#54 add image to use to build the app
  .gitlab-ci.yml
Labels: 2: Dev Review
